site_name: XJTU RC
site_description: A short description of RC project.
site_author: Admin
site_url: https://localhost:7788/
site_dir: site
repo_url: https://github.com/XJRCAdmin/XJTURCDocs
repo_name: XJTURCDocs

theme:
  name: material
  # 下面的logo路径是以docs为根的路径
  logo: static/images/CbiIrobot.svg
  favicon: static/images/favicon.ico
  language: zh
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - navigation.instant
    #- header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy #代码复制
    - content.action.edit
    - content.action.view
    - content.code.annotate

  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: 亮色模式

# extra_javascript:
#   - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  feedback:
    title: 此页面有帮助吗？
    ratings:
      - icon: material/thumb-up-outline #图标可自定义
        name: This page was helpful
        data: 1
        note: >-
          谢谢你的反馈！
      - icon: material/thumb-down-outline
        name: This page could be improved
        data: 0
        note: >-
          Thanks for your feedback! Help us improve this page by
          using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/XJRCAdmin/XJTURCDocs/
      name: XJRCAdmin on GitHub

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2020 - 2025 XJRCAdmin CC BY-SA 4.0

nav:
  - Home: index.md
  - 贡献指南:
      - 贡献指南: blog/contribution/index.md
      - 部署指南: blog/contribution/index2.md
  - 四足组:
      - 四足组: blog/foursteps/index.md
  - 电控组:
      - 新手指南: blog/electronics/freshman/index.md
      - R2上层代码说明: blog/electronics/r2/index.md
  - 视觉组:
      - Introduction: blog/vision/index.md
      - 在windows上搭建cpp环境: blog/vision/windows-cpp/index.md
      - 常用命令汇总: blog/vision/common-command/index.md
      - Markdown: blog/vision/markdown/index.md
      - Bash自学: blog/vision/bash/index.md
      - 硬盘固件等知识: blog/vision/SSD-knowledge/index.md
      - LINUX: blog/vision/linux/linux.md
      - 进程、前后台、服务与例行任务: blog/vision/ustc-linux101-ch4/index.md
      - Git Intro: blog/vision/GitIntro/index.md
      - SSH: blog/vision/ssh&remotessh/index.md
      - 安装lazyvim: blog/vision/lazyvim/index.md
      - 一些现代C++语法特性: blog/vision/ModernCpp/index.md
      - 网线连接树莓派须知: blog/vision/raspberry/index.md
      - Ubuntu VPN: blog/vision/VPN教程/index.md
      - Doxygen与commit规范: blog/vision/Doxygen-commit/index.md
      - Missing Semester qa: blog/vision/qa/index.md
      - CMake Introduction: blog/vision/CMake/index.md
      - Cmake Debug: blog/vision/Debug/index.md
      - Docker & Dev Container: blog/vision/docker/index.md
      - 视觉设备: blog/vision/visualDev/index.md
      - 串口使用: blog/vision/serialUse/index.md
      - blender数据集生成: blog/vision/blender/index.md
      - intel-realsense相机: blog/vision/realsense/index.md
      - Roboflow标注概览: blog/vision/roboflow/Roboflow.md
      - ROS2相关教程: blog/vision/ros2/index.md
      - Navigation 2: blog/vision/Nav2/index.md
      - 强化学习: blog/vision/RL/index.md
      - 队内服务器使用指南: blog/vision/RCserver/index.md
      - 安装队内服务器证书: blog/vision/install-ca-crt/index.md
      - 培训讲稿:
          - index: blog/vision/tutorial/index.md
          - 第一次培训讲稿: blog/vision/tutorial/class1/index.md
          - 第二次培训讲稿: blog/vision/tutorial/class2/index.md
          - 第三次培训讲稿: blog/vision/tutorial/class3/index.md
          - 第四次培训讲稿: blog/vision/tutorial/class4/index.md

  - 机械组:
      - introduction: blog/mechanics/introduction/index.md
      - Example: blog/mechanics/example/index.md
  - 硬件组:
      - Introduction: blog/solid/intro.md
  - 运营组:
      - 运营组: blog/yunying/index.md

plugins:
  - search # 搜索配置
  - glightbox:
      enabled: !ENV [glightbox, false]
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  - minify:
      minify_html: true
  # - git-revision-date-localized:
  #     fallback_to_build_date: true
  #     locale: zh
  # - git-authors:
  #     show_contribution: true
  #     show_line_count: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes
  - def_list
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

  - markdown.extensions.meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: pymdownx.arithmatex.fence_mathjax_format
